### ISSUE TITLE
Use of undeclared identifier 'NSProcessInfo'

### ISSUE THREAD

**Issue by RtzX** [CocoaLumberjack/CocoaLumberjack#975] opened 2018-10-24 05:41 UTC
### New Issue Checklist

* [x] I have read and understood the [CONTRIBUTING guide](https://github.com/CocoaLumberjack/CocoaLumberjack/blob/master/.github/CONTRIBUTING.md)
* [x] I have read the [Documentation](https://github.com/CocoaLumberjack/CocoaLumberjack#documentation) or [CocoaDocs](cocoadocs.org/docsets/CocoaLumberjack)
* [x] I have searched for a similar issue in the [project](https://github.com/CocoaLumberjack/CocoaLumberjack/issues) and found none

### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform Name          |  ios 
 Platform Version        | 11.1
 CocoaLumberjack Version | 3.3.0
 Integration Method     | cocoapods
 Xcode Version          | Xcode 9.1
 Repro rate             | all the time (100%) 

##### Use of undeclared identifier 'NSProcessInfo'

 The simulator is fine, but my Apple phone is problematic.

**Comment by bpoplauschi** [comment] 2018-10-24 08:03
@RtzX this is strange. `NSProcessInfo` is defined for all the platforms, inside `Foundation.framework`. Can you try to delete Derived Data and rebuild? Also, can you add the detailed Xcode error?

**Comment by RtzX** [comment] 2018-10-29 01:59
@bpoplauschi  
Step:
1. clear 'command + shift + k'
2. build 

![b9c1260b-5dd1-41c0-9995-b481744e7b3d](https://user-images.githubusercontent.com/13709644/47625601-124ac200-db61-11e8-9f88-fb86a4a6e7bc.png)

**Comment by bpoplauschi** [comment] 2018-10-29 07:52
@RtzX Command+Shift+K will only trigger an Xcode clean. Use Alt+Command+Shift+K to clear the Derived Data folder.

**Comment by lolgear** [comment] 2018-10-29 09:12
@bpoplauschi 
Not sure, but it is not true anymore with new build system.

**Comment by ffried** [comment] 2018-10-29 09:17
@lolgear It is. In fact it even got better with the new build system. But this is not Xcode 10 yet (in the screenshot). So it does not use the new build system by default.

**Comment by RtzX** [comment] 2018-10-29 09:29
@bpoplauschi 

Step:
1:
```
1. Alt+Command+Shift+K
2. build
results: failure
```
2:
```
clear pod (delete pod)
&&
resume `pod install`
results: failure
```
The same equipment, my colleagues are good!

**Comment by bpoplauschi** [comment] 2018-10-29 09:49
@RtzX which iPhone do you use? What OS version?

**Comment by RtzX** [comment] 2018-10-29 09:59
iPhone version: 11.0.3
xcode: 9.1
CocoaLumberjack: 3.3.0
mac OS:  10.13.4

**Comment by bpoplauschi** [comment] 2018-10-29 10:59
@RtzX I just can't imagine why this error would appear, other than something wrong with Xcode.
Can you try building our demo project and run it on your device, see if maybe the issue manifests in that case?

**Comment by lolgear** [comment] 2018-10-29 11:02
@RtzX 
Could you try to delete derived data folder manually?

Also, I can't assume in which circumstances object in `mainBundle` at "CFBundleIdentifier" is nil.

**Comment by RtzX** [comment] 2018-10-30 01:17
@lolgear 
![12345](https://user-images.githubusercontent.com/13709644/47689303-62d72380-dc24-11e8-967a-84d0c230fbed.png)

I deleted all the datas.
 resume `build`
 results: failure

**Comment by RtzX** [comment] 2018-10-30 01:18
@bpoplauschi 
run demo  `failure`
 
![789](https://user-images.githubusercontent.com/13709644/47689369-a336a180-dc24-11e8-941f-a9cfc3c3b090.png)

**Comment by bpoplauschi** [comment] 2018-10-30 07:37
This is so strange.
Can you try within the file (`DDFileLogger.m`) `#import <Foundation/Foundation.h>`? or something similar.

**Comment by ffried** [comment] 2018-10-30 09:39
@lolgear The matrix won't help much if it's not at all reproducible. I've just successfully built the Benchmark iPhone App against my iPhone using Xcode 9.4.1.

**Comment by ffried** [comment] 2018-10-30 09:44
@RtzX Since you mentioned that it works for your colleagues: can they also build against your iPhone? Assuming your project is under source control, are there any changes on your machine that are not present on other machines? E.g. try a `git reset -xf` (this will reset your repository to a state as if you just cloned it).

**Comment by ffried** [comment] 2018-10-30 09:49
Also, does `Xcode-select -p` point to the right Xcode installation?
Do you have an `/AppleInternal` folder? If so, what's in there?
Can you try and build the following project and see if that works? [MissingNSProcessInfo.zip](https://github.com/CocoaLumberjack/CocoaLumberjack/files/2528978/MissingNSProcessInfo.zip)

**Comment by bpoplauschi** [comment] 2018-10-30 11:07
Thanks @ffried for jumping in, good ideas

**Comment by ffried** [comment] 2018-10-31 08:55
@RtzX Sorry about the project format. Here's one that should also open with Xcode 9.1. 
[MissingNSProcessInfo.zip](https://github.com/CocoaLumberjack/CocoaLumberjack/files/2533462/MissingNSProcessInfo.zip)

**Comment by RtzX** [comment] 2018-10-31 10:06
@ffried 

The same mistake

my iPhone version: 11.0.3

`xcode version`
![1673](https://user-images.githubusercontent.com/13709644/47780994-9d7db080-dd37-11e8-91f2-ca1f1017dc15.png)


`error`
![999901231](https://user-images.githubusercontent.com/13709644/47780916-627b7d00-dd37-11e8-8a12-0d14b8692e75.png)

**Comment by lolgear** [comment] 2018-10-31 14:17
@RtzX 
Could you show all search paths settings with details by level in your project?

I have curious issue in Xcode 9.1 when fresh project build failed with error: "unable to find libSwift*".

**Comment by ffried** [comment] 2018-10-31 14:30
@lolgear It can't really be any changed settings. The project I've attached has no changes to any build settings whatsoever. And I've just successfully built it using Xcode 9.1.

(Apart from that, the issue has nothing to do with Swift, so "unable to find libSwift*" seems unrelated) 😉

**Comment by ffried** [comment] 2018-10-31 14:32
@RtzX Like I just mentioned, I was able to successfully build the sample project using Xcode 9.1.
There really seems to be something off with your machine configuration or build target.
Can you try re-installing Xcode?
If that doesn't work, can you create a new user and try to build the project there?

**Comment by ffried** [comment] 2018-10-31 14:33
@RtzX I'm closing this issue since it has nothing to do with CocoaLumberjack. But feel free to report back.

**Closed by ffried** 2018-10-31 14:33 UTC

**Comment by lolgear** [comment] 2018-10-31 14:36
@ffried 
The error exists in fresh project that was created by Xcode 9.1 and a solution that Apple is provided is "cleanup build settings - library search paths should be empty".

Yes, if you build it correctly, it should be a error-prone setup of Xcode for specific user.

**Comment by RtzX** [comment] 2018-11-01 01:08
@ffried @bpoplauschi 
Thank you very much.About `xcode` version problem. Since we used `Jenkins` to build the version, it is troublesome to upgrade, but I will upgrade the version as soon as possible
