### ISSUE TITLE
iOS 7.1+ app crash with EXEC_BAD_ACCESS in log:(BOOL)asynchronous

### ISSUE THREAD

**Issue by ckrugerS** [CocoaLumberjack/CocoaLumberjack#399] opened 2014-11-14 10:29 UTC
When using Cocoalumberjack in objective-c, I'm getting EXEC_BAD_ACCESS app crash when running background thread that logs info. At the same time the main thread (in a controller) is also logging info. DDLog has been setup plain and simple as described on https://github.com/CocoaLumberjack/CocoaLumberjack and it never crashes on the main thread. Only crashes on the background thread. I have this problem on a bigger app running in production and the crash logs shows exactly the same problem as with my sample app.

I made a very simple project to replicate this problem. I'm using CocoaLumberjack 2.0.0-beta4 and XCode 6.1, running on iOS 7.1 simulator. Source code and readme can be found at https://github.com/ckrugerS/ios-app-crash.git

Please investigate possible bug, but it might be how I'm using the DDLog in the background thread. Any advice?

Thanks

**Comment by oshamsy** [comment] 2015-02-19 10:13
@ckrugerS 
Looking at the sample project, I see the problem is with the run method in the implementation of BackroundProcessor:
```objc
@implementation BackgroundProcessor

BOOL _shouldKeepRunning;

- (void)runAsync {
    DDLogInfo(@"runAsync");
    [NSThread detachNewThreadSelector:@selector(runAsyncThread) toTarget:self withObject:nil];
}

- (void)runAsyncThread {
    DDLogInfo(@"runAsyncThread");
    @autoreleasepool {
        _shouldKeepRunning = YES;
        @try {
            DDLogInfo(@"running it");
            [self run];
        }
        @catch (NSException *ex) {
            DDLogInfo(@"%@",ex.reason);
        }
    }
}

- (void)run {
    
    if (!_shouldKeepRunning)
        return;
    
    DDLogWarn(@"Sync with timestamp");
    
    [NSTimer scheduledTimerWithTimeInterval:1
                                     target:self
                                   selector:@selector(run)
                                   userInfo:nil
                                    repeats:NO];
    
    [[NSRunLoop currentRunLoop] run];
}
```
I think there is a typo in the selector for the timer that is causing the stack to overflow.
Change the selector for the timer to `@selector(runAsync)` to fix this.

**Comment by rivera-ernesto** [comment] 2015-02-19 12:24
Thanks for taking look @oshamsy !

**Comment by bpoplauschi** [comment] 2015-10-21 20:41
Closing based on the latest comments

**Closed by bpoplauschi** 2015-10-21 20:41 UTC
