### ISSUE TITLE
[Question]: Inconsistent behaviour between DDOSLogger & DDASLLogger (Console.app)

### ISSUE THREAD

**Issue by dive** [CocoaLumberjack/CocoaLumberjack#1006] opened 2019-01-04 12:21 UTC
### New Issue Checklist

* [x] I have read and understood the [CONTRIBUTING guide](https://github.com/CocoaLumberjack/CocoaLumberjack/blob/master/.github/CONTRIBUTING.md)
* [x] I have read the [Documentation](https://github.com/CocoaLumberjack/CocoaLumberjack#documentation) or [CocoaDocs](cocoadocs.org/docsets/CocoaLumberjack)
* [x] I have searched for a similar issue in the [project](https://github.com/CocoaLumberjack/CocoaLumberjack/issues) and found none

### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform Name           | iOS
 Platform Version        | 12.1
 CocoaLumberjack Version | 3.4.2
 Integration Method      | Carthage
 Xcode Version           | 10.1
 Repro rate              | 100%
 Demo project link       | code example is below

### Issue Description and Steps

Hello there.

It seems that CocoaLumberjack behaves differently for `DDOSLogger` and `DDASLLogger` in the same situation. For me, all `DDOSLogger` messages that are higher than `DDLogLevelInfo` are missing in Console.app but the same `DDLog*` calls via `DDASLLogger` are okay.

For example, imagine that you have the following functions:
```swift
private func checkDDOSLogger() {
    DDLog.removeAllLoggers()
    DDLog.add(DDOSLogger.sharedInstance)
    self.logEverything()
}

private func checkDDASLLogger() {
    DDLog.removeAllLoggers()
    DDLog.add(DDASLLogger.sharedInstance)
    self.logEverything()
}

private func logEverything() {
    guard let currentLogger = DDLog.allLoggers.first else { fatalError() }
    let prefix = "[x] \(type(of: currentLogger))"
    DDLogDebug  ("\(prefix): DDLogDebug")
    DDLogVerbose("\(prefix): DDLogVerbose")
    DDLogError  ("\(prefix): DDLogError")
    DDLogInfo   ("\(prefix): DDLogInfo")
    DDLogWarn   ("\(prefix): DDLogWarn")
}
```

When I call `checkDDOSLogger()` then I see the following output in Xcode:
> [x] DDOSLogger: DDLogDebug
> [x] DDOSLogger: DDLogVerbose
> [x] DDOSLogger: DDLogError
> [x] DDOSLogger: DDLogInfo
> [x] DDOSLogger: DDLogWarn

but in Console.app I see only this:
> error	12:15:59.528635 +0000	...	[x] DDOSLogger: DDLogError
> info	12:15:59.528868 +0000	...	[x] DDOSLogger: DDLogInfo
> info	12:15:59.529031 +0000	...	[x] DDOSLogger: DDLogWarn

In the situation with `checkDDASLLogger()`, I see this in Xcode:
> [x] DDASLLogger: DDLogDebug
> [x] DDASLLogger: DDLogVerbose
> [x] DDASLLogger: DDLogError
> [x] DDASLLogger: DDLogInfo
> [x] DDASLLogger: DDLogWarn

and in Console.app:
> default	12:18:02.496514 +0000	...	[x] DDASLLogger: DDLogDebug
> default	12:18:02.496714 +0000	...	[x] DDASLLogger: DDLogVerbose
> default	12:18:02.496942 +0000	...	[x] DDASLLogger: DDLogError
> default	12:18:02.497211 +0000	...	[x] DDASLLogger: DDLogInfo
> default	12:18:02.497416 +0000	...	[x] DDASLLogger: DDLogWarn

As you can see, there are no Debug and Verbose message in case of `DDOSLogger` and I'm trying to understand why. Any thoughts?

P.S. This is important to me because historically we use a lot of levels to separate logs in our apps. I recently switched to `DDOSLogger` and now it's almost impossible to use Console.app due to this problem.

**Comment by ffried** [comment] 2019-01-04 12:49
The reason for this lies [here](https://github.com/CocoaLumberjack/CocoaLumberjack/blob/a7491f6c0d56d392ad21ecd68fba8a01c10ad843/Classes/DDOSLogger.m#L60-L73).
`DDOSLogger` logs with the correct levels. While Xcode shows all levels by default, Console.app only shows info and error levels by default. But you can enable debug and verbose messages in Console.app:
In the Action Menu, there are these entries:
<img width="264" alt="image" src="https://user-images.githubusercontent.com/1689782/50688833-81440b80-1027-11e9-9be7-56742019b7b0.png">
If you enable both, you'll also see debug messages.

**Comment by dive** [comment] 2019-01-04 12:55
@ffried, thanks but I forgot to mention that all levels are enabled in Console.app and tried most obvious solutions (change default log level, etc.). Also, in the description, I mentioned that Info messages are visible.

<img width="1064" alt="screenshot 2019-01-04 at 12 52 10" src="https://user-images.githubusercontent.com/59749/50689022-eb58b280-101f-11e9-9eea-0e60abf5568c.png">

**Comment by ffried** [comment] 2019-01-04 13:09
Thanks for clarifying. I just tried to reproduce the problem, but for me all messages show up:
<img width="1949" alt="image" src="https://user-images.githubusercontent.com/1689782/50689521-59a27280-102a-11e9-96b9-838fa21e9f26.png">

**Comment by ffried** [comment] 2019-01-04 13:57
I'm closing this issue, since there's not much CocoaLumberjack can do here. It's up to Apple to fix this. 🙂

**Closed by ffried** 2019-01-04 13:57 UTC

**Comment by dive** [comment] 2019-01-04 14:43
@ffried, thank you, Florian! Let's hope Apple will fix it in the next release.
