### ISSUE TITLE
Legacy Warnings with 2.0.0 and Cocoapods Frameworks 

### ISSUE THREAD

**Issue by justin** [CocoaLumberjack/CocoaLumberjack#481] opened 2015-03-20 14:51 UTC
I'm using Cocoapods 0.36's framework support. The way it imports by default spills my warnings with notices about legacy macros being imported and ambiguous #defines. 

![screen shot 2015-03-20 at 8 49 56 am](https://cloud.githubusercontent.com/assets/1384/6753769/1b54ae3a-cede-11e4-9051-b215a4ef1994.png)

I've tried defining `DD_LEGACY_MACROS` in my code to get around it, but that doesn't seem to pick up in the right spot. Any suggestions?

**Comment by rivera-ernesto** [comment] 2015-03-20 20:59
Import `CocoaLumberjack.h` instead of `DDLog.h` (as explained in the warning messages).

**Comment by justin** [comment] 2015-03-20 21:01
We are using `@import CocoaLumberjack`. The only thing that imports `DDLog.h` file is the umbrella header generated by the Lumberjack pod.

**Comment by rivera-ernesto** [comment] 2015-03-23 12:26
I see. Could you share a sample project with a sample Podfile to reproduce this?

**Comment by MaddTheSane** [comment] 2015-03-23 15:43
Question: Does CocoaPods support module map files? I have the module map file exclude `DDLog+LOGV.h` and `DDLegacyMacros.h` from the module map file, making the use of your own macros possible.

**Comment by MaddTheSane** [comment] 2015-03-23 15:57
Although, looking through Clang's documentation, it seems I may have overlooked some use-cases.

**Comment by rivera-ernesto** [comment] 2015-03-23 19:02
Merged #483. I guess we can't do much more. Thanks @MaddTheSane

**Comment by tapi** [comment] 2015-03-25 16:49
Running into this issue myself, looks like the specification of custom module maps is scheduled for [Cocoapods 0.37.0] (https://github.com/CocoaPods/CocoaPods/issues/3003)

**Closed** 2015-03-26 11:48 UTC

**Comment by FWFabio** [comment] 2015-05-20 10:35
This doesn't seem to fix it with cocoa pods 0.37.1

**Comment by tapi** [comment] 2015-05-20 13:18
The module map is cached and not updated so you may need to delete the module cache on your machine. We had to do this on all our machines including Jenkins and CircleCi.

**Comment by fatuhoku** [comment] 2015-08-06 08:52
@tapi How does one go about deleting the said module cache?

**Comment by tapi** [comment] 2015-08-06 13:06
@fatuhoku `rm -rf ~/Library/Developer/Xcode/DerivedData/ModuleCache` should do the trick

**Comment by fatuhoku** [comment] 2015-08-06 18:52
Sadly that hasn't helped. The warnings still appear.

**Comment by tapi** [comment] 2015-08-06 19:04
I was using a custom pod spec that pointed at the module map in question.
Just tried 
`pod 'CocoaLumberjack/Swift', :git => 'https://github.com/CocoaLumberjack/CocoaLumberjack.git', :branch => 'swift_support'` 
and it worked mind you I am using Cocoapods 0.38.2 now

**Comment by andreyz** [comment] 2015-09-23 13:47
I'm getting the same issue with Cocoapods 0.38.2 and CocoaLumberjack 2.0.1.

Tried deleting module cache, as per @tapi advice. It didn't not affect the issue.
