### ISSUE TITLE
Compilation fails in Xcode 12.5

### ISSUE THREAD

**Issue by xavierLowmiller** [CocoaLumberjack/CocoaLumberjack#1208] opened 2021-02-02 12:13 UTC
### New Issue Checklist

* [x] I have read and understood the [CONTRIBUTING guide](https://github.com/CocoaLumberjack/CocoaLumberjack/blob/master/.github/CONTRIBUTING.md)
* [x] I have read the [Documentation](https://github.com/CocoaLumberjack/CocoaLumberjack#documentation) or [CocoaDocs](cocoadocs.org/docsets/CocoaLumberjack)
* [x] I have searched for a similar issue in the [project](https://github.com/CocoaLumberjack/CocoaLumberjack/issues) and found none

### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform Name           | iOS
 Platform Version        | 11.0 - 14.5
 CocoaLumberjack Version | 3.7.0
 Integration Method      | SPM
 Xcode Version           | Xcode 12.5 beta 1
 Repro rate              | all the time (100%)
 Demo project link       | [CocoaLumberJackRepro.zip](https://github.com/CocoaLumberjack/CocoaLumberjack/files/5910977/CocoaLumberJackRepro.zip)

### Issue Description and Steps

(Xcode 12.5 beta 1, so the issue might change)

I've tried compiling my project that depends on CocoaLumberjack with the new Xcode 12.5 beta:

When compiling, there's an error in `CLIColor.m`'s line 16:
```objc
#if TARGET_OS_OSX
//  ^ 'TARGET_OS_OSX' is not defined, evaluates to 0
```

**Comment by xavierLowmiller** [comment] 2021-02-02 21:46
I find that [adding the import](https://stackoverflow.com/a/37891230/4239752)

```objc
#import <TargetConditionals.h>
```
 solves the issue for me.

Would you be interested in a pull request that adds this?

**Comment by bjhomer** [comment] 2021-02-02 22:01
It's kinda curious that it ever worked, since a few of the files aren't importing Foundation at all before checking the `TARGET_*` conditional. So even if Foundation is importing it, it's not clear that it should apply to the code as currently written.

**Comment by ffried** [comment] 2021-02-02 22:03
Don't we have a Foundation import in the module header? This would make it work because Foundation is then imported before all other headers.

**Comment by bjhomer** [comment] 2021-02-02 22:07
You mean in https://github.com/CocoaLumberjack/CocoaLumberjack/blob/master/Sources/CocoaLumberjack/Supporting%20Files/CocoaLumberjack.h? I don't think that file is automatically imported in all other files; if it were, you would never have write most other imports from within the framework.

**Comment by ffried** [comment] 2021-02-02 22:07
For non-SPM builds, we import Foundation in [this file](Sources/CocoaLumberjack/Supporting Files/CocoaLumberjack.h).

SPM generated its own module header. Not sure, though, if it generates a Foundation import or not.

**Comment by ffried** [comment] 2021-02-02 22:12
Ah you're right. Ignore my last comment. This only applies to (external) module includes, not internally. And we no longer have a PCH.

Like I said, the PR is definitively a good idea. Still curious as to why this suddenly fails, but that's just personal curiosity. 🙃

**Comment by noremac** [comment] 2021-02-24 16:00
Is there a timeline on cutting a release that includes this fix? I've confirmed it fixes things for me locally, thanks for tracking it down!

**Comment by ffried** [comment] 2021-03-02 10:04
I've prepared a release 3.7.1 (#1217). I'm unsure as to when Apple will release 12.5. We might be able to include the scheme update dance for 12.5 in 3.7.1 as well. However, currently 12.5 is still in beta (not even an RC yet).

**Comment by ffried** [comment] 2021-03-02 10:04
I'm closing this issue, since the fix for it is already in `master`.

**Closed by ffried** 2021-03-02 10:04 UTC
