### ISSUE TITLE
call to undeclared function 'DDLoginfo', ISO c99 and later do not support implicit function declarations

### ISSUE THREAD

**Issue by git-timor-hank** [CocoaLumberjack/CocoaLumberjack#1429] opened 2024-11-25 02:18 UTC
**Checklist**
- [x] I have read and understood the [CONTRIBUTING guide](https://github.com/CocoaLumberjack/CocoaLumberjack/blob/master/.github/CONTRIBUTING.md)
- [x] I have read the [Documentation](https://github.com/CocoaLumberjack/CocoaLumberjack#documentation)
- [x] I have searched for a similar issue in the [project](https://github.com/CocoaLumberjack/CocoaLumberjack/issues) and found none

**Describe the bug**
Hi guys , I have a problem with Xcode 16.0  Cocoalumberjack 3.8.5. I cant runing with xcode .  "call to undeclared function 'DDLoginfo', ISO c99 and later do not support implicit function declarations"

**Expected behavior**
Build successed.

**Screenshots**

**Environment info**
  Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform Name           | e.g. ios / macos
 Platform Version        | e.g. 15.0
 CocoaLumberjack Version | e.g. 3.8.5
 Integration Method      cocoapods
 Xcode Version          Xcode 16.0
 Repro rate              all the time (100%)
![Uploading 截屏2024-11-25 09.47.44.png…]()

**Comment by git-timor-hank** [comment] 2024-11-25 02:19
<img width="1440" alt="截屏2024-11-25 09 47 44" src="https://github.com/user-attachments/assets/58f51762-946f-42b3-b17a-963dffb4133e">

**Comment by ffried** [comment] 2024-11-25 06:41
This is usually a missing `#import <CocoaLumberjack/CocoaLumberjack.h>`

**Comment by git-timor-hank** [comment] 2024-11-25 07:12
Where can i input it?  thanks

**Comment by ffried** [comment] 2024-11-25 07:13
At the top of your implementation file (m) - alongside the other imports.

**Comment by git-timor-hank** [comment] 2024-11-25 07:21
I know your means , but it haven't help me resoved. thanks.

**Comment by ffried** [comment] 2024-11-25 07:26
Most of the time it's either a project configuration issue, or an outdated Xcode cache (clean builds might help there).

I'm closing this, since we can't do anything about either of them. If you can reproduce the issue in a small project and upload it here, we're happy to take another look.

**Closed by ffried** 2024-11-25 07:26 UTC
Labels: Bug
