### ISSUE TITLE
Cannot compile with c++ 20 due to deprecated enum-enum conversion 

### ISSUE THREAD

**Issue by buman56** [CocoaLumberjack/CocoaLumberjack#1332] opened 2023-02-23 20:08 UTC
**Checklist**
- [y] I have read and understood the [CONTRIBUTING guide](https://github.com/CocoaLumberjack/CocoaLumberjack/blob/master/.github/CONTRIBUTING.md)
- [y] I have read the [Documentation](https://github.com/CocoaLumberjack/CocoaLumberjack#documentation)
- [y] I have searched for a similar issue in the [project](https://github.com/CocoaLumberjack/CocoaLumberjack/issues) and found none

**Describe the bug**
Our app is running Objective-C++ 17. When we attempt to switch to using c++20. We get an error when

**To Reproduce**
1. Change Xcode project compile ObjectiveC++
2. Change the Xcode project setting to be c++20 [-std=c++20]
3. Create logger 
4. Log message '...' via any of the log macros (DDLogError, DDLogWarn, etc)
5. See compilation fails 

**Expected behavior**
Build should compile 

**Screenshots**
**Bitwise operation between different enumeration types ('const DDLogLevel' and '(unnamed enum at lumberjack/3.7.4/include/CocoaLumberjack/DDLog.h:115:9)') is deprecated
Expanded from macro 'DDLogDebug'
Expanded from macro 'LOG_MAYBE'**

![image](https://user-images.githubusercontent.com/22307415/221018574-201a3dbe-562b-4b84-8859-3369fe335ca4.png)

**Environment info**
  Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform Name           | ios/macos
 CocoaLumberjack Version | 3.7.4
 Integration Method      | manually
 Xcode Version           | Xcode 14.2
 Repro rate              | all the time (100%)

**Comment by ffried** [comment] 2023-02-25 13:56
Are you using 'Treat warnings as errors'? Because when trying to reproduce this, it only shows up as a warning.

**Comment by buman56** [comment] 2023-02-27 18:39
Yes, it would appear the Xcode default is to set 'Treat warnings as errors'.

I've worked around this by doing this:

#pragma clang diagnostic pop
#pragma clang diagnostic ignored "-Wdeprecated-anon-enum-enum-conversion"
#import <CocoaLumberjack/CocoaLumberjack.h>
#pragma clang diagnostic pop

**Comment by buman56** [comment] 2023-02-27 19:13
Ok thanks, your suggestion wrapping it around my macros worked. I'm all set here on my side. Feel free to close this, or I can close it if needed. Thanks

**Comment by ffried** [comment] 2023-02-27 19:23
Great, thanks for the feedback!

I'll close it.

**Closed** 2023-02-27 19:23 UTC
Labels: Bug, Awaiting response

**Comment by LeadAssimilator** [comment] 2023-12-01 06:13
Please reopen this.  This still happens and needs fixed.  Either the macros need changed to suppress the warnings, the macros need to cast the level and flag to their primitives or to one another to avoid the warnings, or the level and flag need to be redefined so they are the same (i.e. NS_OPTIONS and NS_ENUM are not the same - NS_OPTIONS is defined as an anon enum while NS_ENUM is named, which leads to the warning)!

We shouldn't all have to workaround this given it is an issue with how the macros are playing fast and loose with the level and flag types.

**Comment by ffried** [comment] 2023-12-07 15:09
@LeadAssimilator This is fixed on `master` now.

**Comment by LeadAssimilator** [comment] 2023-12-08 04:27
@ffried great, thanks!
