### ISSUE TITLE
Include of non-modular header compile error with 2.0.1

### ISSUE THREAD

**Issue by parfeon** [CocoaLumberjack/CocoaLumberjack#544] opened 2015-06-25 09:40 UTC
After update to **2.0.1** I get this errors in [_CocoaLumberjack_](https://github.com/CocoaLumberjack/CocoaLumberjack/blob/master/Classes/CocoaLumberjack.h#L68-L80) for all highlighted imports.
CocoaLumberjack declared `s.dependency 'CocoaLumberjack', '~> 2.0'` in our SDK pod spec. When it is pulled with `pod install` into target project with **2.0.1** we start getting those errors.

What exactly has been changed in CocoaLumberjack structure?

**Comment by pbenkoe** [comment] 2015-06-25 11:18
+1

**Comment by bpoplauschi** [comment] 2015-06-25 11:48
The only error I got was due to `ddLogLevel` missing. See https://github.com/CocoaLumberjack/CocoaLumberjack/issues/542 for that

**Comment by plandem** [comment] 2015-06-25 11:53
looks like same issue. now i had to set: 

s.dependency 'CocoaLumberjack', '2.0.0'

**Comment by pbenkoe** [comment] 2015-06-25 11:58
i get the error with the swift_2.0 branch as well.. (version 2.0.0)

pod 'CocoaLumberjack', :git=> 'https://github.com/CocoaLumberjack/CocoaLumberjack', :branch => 'swift_2.0'

**Comment by ranunez** [comment] 2015-06-25 21:30
Same issue here

**Comment by Buju77** [comment] 2015-06-26 08:58
same issue here. i have to set the dependency to fixed '2.0.0' like @plandem

**Comment by diejmon** [comment] 2015-06-26 14:16
Same issue.

**Comment by jtdavid** [comment] 2015-06-27 19:07
Same.

**Comment by franklsf95** [comment] 2015-06-29 16:36
+1

**Comment by rivera-ernesto** [comment] 2015-06-29 16:46
Hopefully someone can figure this out and make a pull request as at the moment I am not using the library.

**Comment by jmkk** [comment] 2015-07-02 17:33
+1

**Comment by mlintz** [comment] 2015-07-04 02:29
+1

**Comment by rvi** [comment] 2015-07-07 17:36
same for me.

**Comment by cpacciarini** [comment] 2015-07-09 21:24
Same here.

**Comment by ide** [comment] 2015-07-15 22:00
This appears to have been fixed in master. @rivera-ernesto @bpoplauschi could you please publish a new release to CocoaPods?

**Comment by irace** [comment] 2015-07-16 00:26
:+1: Please please please publish a new CocoaPods release.

**Comment by rivera-ernesto** [comment] 2015-07-17 13:10
You can start using the latest commits right away with `pod 'CocoaLumberjack', :head` while @bpoplauschi decides we're good for an official release.

**Comment by diejmon** [comment] 2015-07-17 13:16
Thanks for the tip!

**Comment by bpoplauschi** [comment] 2015-07-17 13:37
@rivera-ernesto we have a very small number of changes on master since 2.0.1, but we can definitely release a small patch (2.0.2). Biggest thing would be the the Swift 1.2 fixes.

As for the next release, 2.1.0 with Swift support, I'm not sure what's left to be done there.

About Swift 2.0 (separate branch), is that planned to be merged (into the Swift support branch) after an official release of Xcode 7?

**Comment by rivera-ernesto** [comment] 2015-07-17 13:41
I think that we need a 2.0.x release soon that fixes backwards compatibility (`ddLogLevel`) that got broken in 2.0.1.

We can still use the new level code in a 2.1.0 release.

**Comment by bpoplauschi** [comment] 2015-07-17 13:59
We don't have a fix to that issue yet, and from what I remember, we can't fix it in 2.0.x as that is a patch and we would break compatibility with 2.0.1

**Comment by jmkk** [comment] 2015-07-17 16:36
@bpoplauschi but isn't this a regression in 2.0.1 since people are not seeing this error in 2.0.0?
That would mean the fix needs to go in 2.0.x as well.

**Comment by Buju77** [comment] 2015-07-17 17:15
@bpoplauschi 2.0.2 wouldn't break anything with 2.0.1 because 2.0.1 is already broken and not usable (compiler error).

as far as I know, everyone is either using fixed version 2.0.0 or using :head. So 2.0.2 needs to be released first with the fix for broken 2.0.1.

**Comment by rivera-ernesto** [comment] 2015-07-20 13:58
Yes, we need to fix 2.0.1 API incompatibility in 2.0.2 first. Then we can "break" it again with 2.1.0.

**Comment by ide** [comment] 2015-07-20 15:46
Since :head is a breaking change compared to 2.0.0, it should probably be published as 3.0.0 so that everyone with "~> 2.0" in their Podfile doesn't automatically get this change when running "pod update".

The changelog between 2.x and 3.x will be quite small but it should help reduce a lot of issues like this one where people find their code is not compiling after updating to the latest minor/patch version. The major version bump helps set expectations that old code might not compile without some modifications.

**Comment by rivera-ernesto** [comment] 2015-07-20 16:02
2.1.0 should be enough. 2.0.0 was a major refactoring, 3.0.0 wouldn't be one.

People who don't expect any API should use `~> 2.x.x` and not `~> 2.x`.

**Comment by ide** [comment] 2015-07-20 16:06
OK. The readme should communicate that clearly since the rest of CocoaPods (and npm and anything following semver really) treats 2.0 to 2.1 as a backwards-compatible change, and the CocoaPods site tells users to use `pod 'CocoaLumberjack', '~> 2.0'`.

**Comment by rivera-ernesto** [comment] 2015-07-20 16:11
Cocoapods [documentation](https://guides.cocoapods.org/making/making-a-cocoapod.html) already does that.

More generally the problem lays on libraries "requiring" CocoaLumberjack. The library shouldn't be a requirement but only used when explicitly added by the user who would choose whatever version prefers.

**Comment by mporeh** [comment] 2015-07-22 18:06
Include of non-modular header compile error  also happens to me on my swift project
managed to solve it by creating an umbrella header for cocoa lumberjack and updating the module map accordingly if you check the pod lib 'SWRevealViewController' you will see how it is supposed to be done

**Comment by rivera-ernesto** [comment] 2015-07-23 12:32
@mporeh A pull request would be greatly appreciated.

**Comment by fjsosa** [comment] 2015-07-23 17:51
+1, please!

**Comment by thomasaw** [comment] 2015-07-27 07:10
Even after switching to 2.0.0 I had to delete ~/Library/Developer/Xcode/DerivedData/ to get the build working again. However, once I got the build working again I don't get the build error after switching back to 2.0.1.

**Comment by tbaranes** [comment] 2015-08-16 17:13
Any release coming soon about this?

**Comment by djtarazona** [comment] 2015-08-16 21:47
+1

**Comment by bpoplauschi** [comment] 2015-10-21 20:32
There were a few releases after this. Please check them and we will reopen the issue if it still occurs.

**Closed by bpoplauschi** 2015-10-21 20:32 UTC
Labels: Bug
