### ISSUE TITLE
Crash in -isLogFile (DDFileLogger.m)

### ISSUE THREAD

**Issue by nonstriater** [CocoaLumberjack/CocoaLumberjack#548] opened 2015-07-01 09:03 UTC
![image](https://cloud.githubusercontent.com/assets/3192105/8450930/b9af9cbe-2011-11e5-8760-ca231712f825.png)

stack varibles:
![image](https://cloud.githubusercontent.com/assets/3192105/8451595/f92f053c-2016-11e5-8e4a-703ecbb099c9.png)

any help?

**Comment by rivera-ernesto** [comment] 2015-07-01 13:48
Probably a duplicate of #33 and #81.

**Comment by bpoplauschi** [comment] 2015-10-24 08:25
@nonstriater could you setup a demo project where the crash is reproducible? I was looking at the code and can't figure out a crash scenario there.

**Comment by rivera-ernesto** [comment] 2015-10-26 13:43
We had many releases after this. Let's close it and reopen if new reports arise.

**Closed by rivera-ernesto** 2015-10-26 13:43 UTC
Labels: Awaiting response
