### ISSUE TITLE
DDFileLogger localizes file names and timestamps

### ISSUE THREAD

**Issue by UrK** [CocoaLumberjack/CocoaLumberjack#1147] opened 2020-06-09 11:13 UTC
### New Issue Checklist

* [X] I have read and understood the [CONTRIBUTING guide](https://github.com/CocoaLumberjack/CocoaLumberjack/blob/master/.github/CONTRIBUTING.md)
* [X] I have read the [Documentation](https://github.com/CocoaLumberjack/CocoaLumberjack#documentation) or [CocoaDocs](cocoadocs.org/docsets/CocoaLumberjack)
* [X] I have searched for a similar issue in the [project](https://github.com/CocoaLumberjack/CocoaLumberjack/issues) and found none

### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform Name           | iOS
 Platform Version        | 13.5
 CocoaLumberjack Version | 3.6.1
 Integration Method      | cocoapods
 Xcode Version           | Xcode11.5
 Repro rate              | 100%
 Demo project link       | 

### Issue Description and Steps

DDFileLogger stores the files with names and timestamps in localized format.
- Change the device to Arabic
- Setup DDFileLogger and run the app.
- Log files created on disk have localized names, e.g. `diagnostic_٢٠٢٠-٠٦-٠٩_١٢_٣٣_٥٣.txt`
- Timestamps in the files have localized format, e.g. `(I) ٢٠٢٠-٠٦-٠٩ ١٠:٢٢:٤١ +0000 BtAppDelegate:476 Hello from app`

As the logs are used by the developer of the app and not the end user, they should not be localized. Localization makes the files unreadable to developer.

**Comment by ffried** [comment] 2020-07-15 09:05
@UrK Thanks for reporting this. However, I cannot reproduce _all_ of the issues you described.

It's true, that `DDLogFileFormatterDefault` was localizing the timestamps (fixed by #1151). However, you need to manually set it on the `DDFileLogger`. By default, no timestamps are added to messages logged by `DDFileLogger`.

Next, log files created on disk already take care of not localizing the timestamps. Given your example (`diagnostic_....txt`) I'm assuming you're using your own `DDLogFileManager`? The `DDLogFileManagerDefault` would create log files that follow this pattern: `$AppName $TimeStamp.log` The `$TimeStamp` is _not_ localized in this case.

**Closed** 2020-07-16 09:48 UTC
Labels: Bug
