### ISSUE TITLE
CocoaLumberjack ignores globally defined log level (2.0.0)

### ISSUE THREAD

**Issue by Ziewvater** [CocoaLumberjack/CocoaLumberjack#510] opened 2015-05-14 21:22 UTC
**Note:** I'm using CocoaLumberjack 2.0.0
CocoaLumberjack seems to be ignoring the globally defined log level I've set. I've tried the following:
* Setting `DDLogLevel ddLogLevel = SomeLogLevel` after `#import <CococaLumberjack/CocoaLumberjack.h>` in a `.pch` prefix file
* Defining `DDLogLevel ddLogLevel;` in a `.h` file after `#import <CocoaLumberjack/CocoaLumberjack.h>`, and giving it a value in the corresponding `.m`, as mentioned [here](http://stackoverflow.com/a/26908419/2383003). The aforementioned header is imported wherever logging is used.
* In your README, you mention defining `LOG_LEVEL_DEF` before importing CocoaLumberjack, so I tried that with the following
``` objective-c
#import <CocoaLumberjack/DDLog.h> // This is to get the DDLogLevel values
DDLogLevel ddLogLevel = DDLogLevelWarning;
#define LOG_LEVEL_DEF ddLogLevel

#import <CocoaLumberjack/CocoaLumberjack.h>
```

In each case, my definition is either ignored and the global log level falls back onto `DDLogLevelVerbose`, or the build fails with linking error (that's what happened with the weird pre-import `LOG_LEVEL_DEF` code).

The only solution I've found to setting a global log level is the following:
``` objective-c
#import <CocoaLumberjack/CocoaLumberjack.h>

#undef LOG_LEVEL_DEF
#define LOG_LEVEL_DEF DDLogLevelWarning
```
After that, the log level I want is actually obeyed. As far as I can tell, DDLogMacros.h:30 is being evaluated before my `ddLogLevel` variable is defined, and any time I try and set it in the future it's not being considered by any logging functions.

What is going on here? What am I doing wrong in trying to set the global log level? I'm trying to find help through your documentation but nothing is really helping me.

**Comment by rivera-ernesto** [comment] 2015-05-15 12:37
This is a duplicate of #478. Please next time use existing issues before opening new ones, that helps everyone.

You are `#import`ing (`DDLog.h`) before `#define`. Also you shouldn't import that file manually unless you need 1.9.x legacy mode.

```obj-c
#define LOG_LEVEL_DEF ddLogLevel
#import <CocoaLumberjack/CocoaLumberjack.h>

DDLogLevel ddLogLevel = DDLogLevelWarning;
```

Should work.

**Closed by rivera-ernesto** 2015-05-15 12:37 UTC

**Comment by Ziewvater** [comment] 2015-05-15 19:59
Sorry about not using the existing issue; I had seen it when trying to find a solution but didn't understand it.

I tried the solution you posted above, but I get the same linking error that I had when I tried a similar thing  but imported `DDLog.h` first. I looked through my workspace and it doesn't look like I have any explicit imports of `DDLog.h` anywhere in the workspace, except for in the CocoaLumberjack pod project.

**Comment by rivera-ernesto** [comment] 2015-05-15 20:08
No problem.

What is your liker error? Maybe we have a similar issue for that too ;)

**Comment by Ziewvater** [comment] 2015-05-15 20:24
I get a lot of errors like this
```
duplicate symbol _ddLogLevel in:
    /Users/JeremyYL/Library/Developer/Xcode/DerivedData/Celly-fsmbqjjckrmddldfpfkbaihjbtdd/Build/Intermediates/Celly.build/Debug-iphonesimulator/Celly.build/Objects-normal/x86_64/CLMemberInfoViewController.o
    /Users/JeremyYL/Library/Developer/Xcode/DerivedData/Celly-fsmbqjjckrmddldfpfkbaihjbtdd/Build/Intermediates/Celly.build/Debug-iphonesimulator/Celly.build/Objects-normal/x86_64/CLAppDelegate.o
```
There's no mention of `ddLogLevel` in any of these files. I'm not familiar with the linking process so I don't really know what this stuff means.

**Comment by rivera-ernesto** [comment] 2015-05-18 12:28
Check where you define `ddLogLevel`. Sounds like there are two conflicting definitions.

**Comment by Ziewvater** [comment] 2015-05-20 22:22
I've checked where `ddLogLevel` is being defined, and in my project it's only in one file, set up as the following:
``` objective-c
#if DEBUG
    #define LOG_LEVEL_DEF DDLogLevelDebug
#else
    #define LOG_LEVEL_DEF DDLogLevelDebug
#endif
```

The only other places where `ddLogLevel` is mentioned in my workspace are in the CocoaLumberjack pod, and in MagicalRecord. In MagicalRecord it's referred to in the following:
``` objective-c 
// In MagicalRecord.h:23
#if MR_ENABLE_ACTIVE_RECORD_LOGGING != 0
      // First, check if we can use Cocoalumberjack for logging
    #ifdef LOG_VERBOSE
        extern int ddLogLevel;
        #define MRLog(...)  DDLogVerbose(__VA_ARGS__)
    #else
        #define MRLog(...) NSLog(@"%s(%p) %@", __PRETTY_FUNCTION__, self, [NSString stringWithFormat:__VA_ARGS__])
    #endif
#else
    #define MRLog(...) ((void)0)
#endif
```

**Comment by MaddTheSane** [comment] 2015-05-20 22:45
@rivera-ernesto Unfortunately, if you import Modules (or use Swift), you will have to define `LOG_LEVEL_DEF` on the command line. See my comments on #478.

**Comment by rivera-ernesto** [comment] 2015-05-21 12:34
I see. Then probably we need to add that to the README.
