### ISSUE TITLE
crash in -[DDLogMessage initWithMessage:level:flag:context:file:function:line:tag:options:timestamp:]

### ISSUE THREAD

**Issue by CLuRoad** [CocoaLumberjack/CocoaLumberjack#1350] opened 2023-07-25 09:32 UTC
**Describe the bug**
崩溃标识	mach
崩溃类型	EXC_BAD_ACCESS (SIGSEGV)
崩溃子类型	KERN_INVALID_ADDRESS
崩溃地址	0x0000000149a06ff0
崩溃诊断	Attempted to dereference garbage pointer 0x149a06ff0.
Originated at or in a subcall of unknown, cannot find symbol

0	libsystem_platform.dylib	__platform_strlen()         
1	CoreFoundation	___CFStringAppendFormatCore()         
2	CoreFoundation	__CFStringCreateWithFormatAndArgumentsReturningMetadata()         
3	CoreFoundation	__CFStringCreateWithFormatAndArgumentsAux2()         
4	Foundation 		-[NSString initWithFormat:]()  
5	MyApp			-[DDLogMessage initWithMessage:level:flag:context:file:function:line:tag:options:timestamp:](DDLog.m:1152)

**Environment info**
  Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform Name           | ios
 Platform Version        |  16.0+
 CocoaLumberjack Version | 2.4.0.9
 Integration Method      | cocoapods
 Xcode Version           | Xcode 14.3
 Repro rate              | sometimes 5%

**Additional context**
Only crash on iOS 16+

**Comment by CLuRoad** [comment] 2023-07-25 09:34
这是ChatGPT告诉我的答案，但还没有验证是否正确
![screencapture-chat-openai-2023-07-25-17_15_08](https://github.com/CocoaLumberjack/CocoaLumberjack/assets/15317617/f4f66ed4-3b96-455b-8370-79e67480a2b3)

**Comment by ffried** [comment] 2023-07-26 05:28
> CocoaLumberjack Version | 2.4.0.9

That is a rather old version. I think we fixed crashes in the format initializer a while back. Can you please try to upgrade to a newer version? Preferably 3.8.0?

**Comment by CLuRoad** [comment] 2023-07-26 14:03
@ffried Hi！
Due to version rhythm constraints, the version cannot be updated immediately.So what is the reason for this crash and how to solve it in the new version?

Multiple online crashes occurred in this line
`[[NSString alloc] initWithFormat:@"%s", dispatch_queue_get_label(DISPATCH_CURRENT_QUEUE_LABEL)];`
At present, my guess is that in the current NSOperation `dealloc` stage, the above code will cause `KERN_INVALID_ADDRESS`, I am using demo verification, trying to reproduce

**Comment by xlnevermore** [comment] 2023-08-03 10:55
My Version is 3.8.0, Had crashed log some msg like  this:   @CLuRoad @ffried 

**DDLogInfo(@"aaa%d%@aaaa");**

**Comment by ffried** [comment] 2023-08-05 13:24
`DDLogInfo(@"aaa%d%@aaaa")` is not a valid log statement. There are two placeholders (`%d` and %@`) that do not have corresponding values.

**Comment by qianshang** [comment] 2023-08-28 09:13
The code snippet you provided seems to have a slight issue. The method dispatch_queue_get_label returns a C string (const char *), and you're trying to assign it directly to an NSString object. This would result in a type mismatch. To fix this issue, you need to convert the C string to an NSString. Here's the corrected version of the code:

const char *queueLabelCString = dispatch_queue_get_label(DISPATCH_CURRENT_QUEUE_LABEL);
NSString *queueLabel = [NSString stringWithUTF8String:queueLabelCString];

In this corrected version, the C string returned by dispatch_queue_get_label is converted to an NSString using the stringWithUTF8String: method. This way, you ensure that the queue label is properly stored as an NSString object.

**Comment by ran-helfer** [comment] 2023-09-03 14:37
I am experiencing this crash when trying to send some response as a string using:

```
let messageWithBody = "[Network] Response id \(identifier) \(response.statusCode) \(stripped) headers: \(headersString) body: \(dict)"
DDLogInfo(messageWithBody)

```

The `messageWithBody` is a String with value - not empty and `nil`

![Screenshot 2023-09-03 at 17 34 50](https://github.com/CocoaLumberjack/CocoaLumberjack/assets/83655810/c47131d2-ac34-4fc6-bb57-1c8e30795c4e)

**Comment by ffried** [comment] 2023-09-04 05:58
@ran-helfer I'm not sure there is something we can do. There's only one frame where our code is involved and that one's doing practically nothing. Also, in the current version of CocoaLumberjack, we're not even calling `String.init(format:arguments:)` anymore. Can you check if you still see these crashes using the latest version of CocoaLumberjack?

**Comment by ran-helfer** [comment] 2023-09-05 07:35
@ffried Seem like the issue is being caused when i use latest CocoaLumberjack version. When i am using version 3.7.4 - all is ok and i do not experience this crash.

**Comment by ran-helfer** [comment] 2023-09-05 07:39
@ffried - yes 3.8.1 🙇🏻

**Comment by ffried** [comment] 2023-09-05 07:42
Ok, thanks for confirming.

Since I cannot seem to reproduce the issue here, a reproduction-project would be very helpful to get this resolved.

**Comment by ran-helfer** [comment] 2023-09-05 07:57
still investigating this.  will circle back to you when more data is available - Thanks 🙏🏻

**Comment by ran-helfer** [comment] 2023-09-06 11:46
@ffried we have managed to reproduce this constantly on our medical application:

![Screenshot 2023-09-06 at 13 22 31](https://github.com/CocoaLumberjack/CocoaLumberjack/assets/83655810/48bda09f-2966-4d40-a8b2-d53ec89601b9)

This is the string which is causing a crash on version 3.8.1 of `CocoaLumberjack`
[crashing_login_response.txt](https://github.com/CocoaLumberjack/CocoaLumberjack/files/12536899/crashing_login_response.txt)

**Comment by ran-helfer** [comment] 2023-09-06 12:00
It also seem that if we send this string which contains space at the beginning and at the end `CocoaLumberjack` crashes:

`" \"https://dl.dropbox.com/sh/9jh1axl3soqi6px/AACNAKPwS_SydghjH2sH2hKba/LVO/amalgamated%20LVO%20Users%20Guide.pdf?dl=1\";\n                        format = \"--Censored--\";\n                        name = \"--Censored--\";\n                        url = \"about/userguide?viz_product=lvo&client_version=1.90.0\";\n                    };\n                    11 =                     {\n                        \"dropbox_url\" = \"https://dl.dropbox.com/s/uf1c39k23omch3t/IFU-0093%20Viz%20REP%20User%27s%20Guide.pdf?dl=0\";\n "`

and if we remove the space in the beginning and at the end of the string `CocoaLumberjack` does not crash

it seem much related to `CocoaLumberjack` changes applied here:
https://github.com/CocoaLumberjack/CocoaLumberjack/pull/1347/files

**Comment by ffried** [comment] 2023-09-06 12:14
@ran-helfer thanks, much appreciated!

Just to confirm: is the `args` array empty in the messages that crash?

**Comment by ran-helfer** [comment] 2023-09-06 12:36
@ffried - you are welcome 

We appreciate your work here :) 

The `args` contain data like in the file previously attached [crashing_login_response.txt](https://github.com/CocoaLumberjack/CocoaLumberjack/files/12536899/crashing_login_response.txt)

**Comment by ran-helfer** [comment] 2023-09-06 12:38
We did not change anything on our side. Same code base that worked before 3.8.1 suddenly began to crash when we got the update. 

We did not lock `CocoaLumberjack` to 3.7.4 or any other version

**Comment by ffried** [comment] 2023-09-06 15:52
@ran-helfer Unfortunately, I haven't been able to replicate the crashes directly. However, your sample message pointed me to a potential issue that I fixed in bc152f6. Do you think you can try to test with the current `master` branch?

I've also added a bunch of more tests in this commit - that are all green. Especially the issue with spaces at the beginning or end of a message is something I couldn't reproduce.

Do you think you are able to provide me with a code snippet in the following form that I can put into a test to replicate the crash?
```swift
import CocoaLumberjackSwift

let arg0 = "ABC"
let arg1 = 123
DDLogError("Some message with \(arg0) and \(arg1) that causes a crash")
```

Of course you can adjust the message format and use as many args as needed. The only requirement is that it has no outside dependencies. If structs / classes are needed as args, I'd ask you to replicate them in the snippet as well, so that I can put them in a replication test.

**Comment by morluna** [comment] 2023-09-27 18:58
Just wanted to drop a message that we also started noticing crashed from our Xcode organizers around logging objects errors directly:

So something like `DDLogError(error)` where error is something from the `catch` block is giving us crashes like:

<img width="746" alt="Screenshot 2023-09-27 at 12 53 23 PM" src="https://github.com/CocoaLumberjack/CocoaLumberjack/assets/8826948/62c000da-3aea-4ceb-b4e9-fd9fb32459c6">


We just upgraded to version 3.8.1 and were on 3.7.4 previously.  I thought of following the deprecation warning suggestion on Xcode 15 RC:

<img width="355" alt="Screenshot 2023-09-27 at 12 56 07 PM" src="https://github.com/CocoaLumberjack/CocoaLumberjack/assets/8826948/45822e00-faf0-4ad2-b573-8e5e457178b4">

But we have so many of these log statements it's kind of a nightmare to fix by doing something like:

```swift
DDLogError("\(error.localizedDescription)")
```

**Comment by morluna** [comment] 2023-09-27 19:12
Actually a small update to my previous comment ^ @ffried CC @ran-helfer: We actually upgraded from 3.8.0 and we didn't see any deprecation warnings or crashes on this version before.

**Comment by ffried** [comment] 2023-10-09 09:46
@morluna 

> But we have so many of these log statements it's kind of a nightmare to fix by doing something like:

For errors, you could define yourself a convenience function like this:
```swift
func DDLogError<E: Error>(_ error: E,
                          file: StaticString = #file,
                          function: StaticString = #function,
                          line: UInt = #line) {
     DDLogError("\(error)", file: file, function: function, line: line)
}
```

But I'd generally recommend adding a message anyways, like:

```swift
DDLogError("My operation failed: \(error)")
```


> So something like DDLogError(error) where error is something from the catch block is giving us crashes like:

Can you try the current `master` branch please? As mentioned in [my previous comment](https://github.com/CocoaLumberjack/CocoaLumberjack/issues/1350#issuecomment-1708652714), I've made a few fixes that I'd like to verify before releasing.
Also, if you still see the crashes, please post _all_ frames leading up to the crash. In your screenshot, it only shows the frames as of `#4` of Thread 1.

**Comment by hootigger** [comment] 2023-10-30 02:36
"Excuse me, is there a temporary solution to this problem in Xcode 15?"

**Comment by hootigger** [comment] 2023-10-30 05:46
"I forked the repository, generated the podspec, and then directly referenced it in my project. After that, the crash, where `String(formate: storage.formate, aguments: storage.args)`, which I was experiencing on iOS 16 simulator, disappeared. This temporarily solved my problem."

**Comment by ffried** [comment] 2023-10-31 08:32
@hootigger Thanks for confirming. I think this one should be fixed on `master` then. I'll release this in a new bugfix version today.

**Closed by ffried** 2023-10-31 08:32 UTC
Labels: Bug
