### ISSUE TITLE
Can't use @import Cocoalumberjack

### ISSUE THREAD

**Issue by dnkoutso** [CocoaLumberjack/CocoaLumberjack#537] opened 2015-06-22 22:41 UTC
The published podspec includes the s.module_map file but in a sample app I am using 

```objc
@import Cocoalumberjack
```

And receiving an error "Module `Cocoalumberjack` not found".

```ruby
Pod::Spec.new do |s|
  s.name         = "CocoaPodsLocalLibrary"
  s.version      = "1.0.0"
  s.summary      = "Sample"
  s.homepage     = "REDACTED"
  s.author       = { "REDACTED" => "redacted@redacted.com" }
  s.source       = { :git => "redacted.git", :tag => "podify/#{ s.version.to_s }", :submodules => true }
  
  s.platform = :ios
  s.ios.deployment_target = "8.0"
  
  s.dependency 'CocoaLumberjack', '~> 2.0.0'

  s.source_files = "CocoaPodsLocalLibrary/*.{h,m}"
end
```

![screen shot 2015-06-22 at 3 59 21 pm](https://cloud.githubusercontent.com/assets/310370/8295258/ae50230a-18f7-11e5-80e5-f163db63b580.png)

By the way I am trying to consume it in a library project (another .podspec) not in an app.

Am I doing something wrong?

**Comment by dnkoutso** [comment] 2015-06-22 23:01
I am not sure this is a Cocoalumberjack specific issue...could be the way I am consuming or setting up my project.

How would you link this without cocoapods?

**Comment by rivera-ernesto** [comment] 2015-06-23 15:18
Duplicate of https://github.com/CocoaLumberjack/CocoaLumberjack/issues/405#issuecomment-74428466.

**Closed by rivera-ernesto** 2015-06-23 15:18 UTC
Labels: Bug

**Comment by dnkoutso** [comment] 2015-06-23 15:27
For anyone who hits this in the future, see my comment in #405.
