### ISSUE TITLE
Can't build project on Xcode 12 beta

### ISSUE THREAD

**Issue by odarynakorolevych** [CocoaLumberjack/CocoaLumberjack#1160] opened 2020-08-07 08:40 UTC
### New Issue Checklist

* [x] I have read and understood the [CONTRIBUTING guide](https://github.com/CocoaLumberjack/CocoaLumberjack/blob/master/.github/CONTRIBUTING.md)
* [x] I have read the [Documentation](https://github.com/CocoaLumberjack/CocoaLumberjack#documentation) or [CocoaDocs](cocoadocs.org/docsets/CocoaLumberjack)
* [x] I have searched for a similar issue in the [project](https://github.com/CocoaLumberjack/CocoaLumberjack/issues) and found none

### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform Name           | iOS
 Platform Version        | 14.0
 CocoaLumberjack Version | 3.6.2
 Integration Method      | CocoaPods
 Xcode Version           | Xcode 12 beta 4
 Repro rate              | 100%

### Issue Description and Steps

Xcode 12 beta 4 can't find the module CocoaLumberjack. Please add support of it.

**Comment by ffried** [comment] 2020-08-14 13:12
For Xcode 12 support, you need to use the `master` branch.
Also, there is #1161 which might be the same issue.

**Comment by shikhil-sevenlakes** [comment] 2020-08-25 12:13
I am also facing the same issue. Please check

```
Showing All Messages
~/Logging Manager/LogManager.h:15:9: 'CocoaLumberjack/CocoaLumberjack.h' file not found

Failed to emit precompiled header '~/Xcode/DerivedData/ABC-fgropwrduxzlubdcsarmrrumkcwd/Build/Intermediates.noindex/PrecompiledHeaders/App Stage-Bridging-Header-swift_26K6PXALQ98NL-clang_1EJ4IRL0H586Y.pch' for bridging header '~/Models/App Stage-Bridging-Header.h'


```

**Comment by ffried** [comment] 2020-08-25 12:46
@shikhil-sevenlakes Can you provide a few details? What integration method are you using? What "version" of CocoaLumberjack (you should be using the current `master` branch).

**Comment by shikhil-sevenlakes** [comment] 2020-08-25 13:19
> @shikhil-sevenlakes Can you provide a few details? What integration method are you using? What "version" of CocoaLumberjack (you should be using the current `master` branch).


Info | Value
-- | --
Platform Name | iOS
Platform Version | 14.0
CocoaLumberjack Version | 3.6.2
Integration Method | CocoaPods
Xcode Version | Xcode 12 beta 5


I am using the master branch -
`pod 'CocoaLumberjack/Swift',:git => 'https://github.com/CocoaLumberjack/CocoaLumberjack.git', :branch => 'master'`

**Comment by shikhil-sevenlakes** [comment] 2020-08-26 09:39
@ffried - I am still facing the same issue in Xcode 12 beta 6 as well.

**Comment by sushichop** [comment] 2020-08-26 11:54
Now I confirmed I was able to build a small sample project below.
So I don't think this is `directly` related to CocoaLumberjack's issue.
Please confirm you set `SWIFT_VERSION` to your Xcode project. Or can you make a small project for repro?

Info | Value
-- | --
Platform Name | iOS
Platform Version | 14.0
CocoaLumberjack Version | [master branch](https://github.com/CocoaLumberjack/CocoaLumberjack/commit/c467e54ed279dbba5f86b5f280359bf6638e2623)
Integration Method | CocoaPods 1.9.3
Xcode Version | Xcode 12 beta 6

Podfile
```ruby
platform :ios, '10.0'

target 'SampleSwiftApp' do
  use_frameworks!
  pod 'CocoaLumberjack/Swift', :git => 'https://github.com/CocoaLumberjack/CocoaLumberjack.git'
end
```

ViewController.swift
```swift
import UIKit
import CocoaLumberjack

class ViewController: UIViewController {
    override func viewDidLoad() {
        super.viewDidLoad()
        dynamicLogLevel = .info
        DDLog.add(DDOSLogger.sharedInstance)
        DDLogVerbose("verbose")
        DDLogDebug("debug")
        DDLogInfo("info")
        DDLogWarn("warn")
        DDLogError("error")
    }
}
```

**Comment by ffried** [comment] 2020-08-26 11:58
@sushichop Thanks for confirming. I was _just_ trying to do the same, but failed at installing CocoaPods (which seems to be related to Big Sur, though).

**Comment by sushichop** [comment] 2020-08-26 12:04
@ffried I see! My environment is Catalina(mac OS 10.15.6)🙂

**Comment by shikhil-sevenlakes** [comment] 2020-08-26 17:41
@ffried @sushichop  - Thanks. The **SWIFT_VERSION** of the project is Swift 5. 

I am able to build the app for the device but it fails to compile for simulators. It gives header file not found.

Not sure if this is related to Cocoalumberjack or I need to change some project settings.

**Comment by glorysaber** [comment] 2020-09-02 19:01
I am having the same problem too but with SPM.

**Comment by shikhil-sevenlakes** [comment] 2020-09-03 04:37
@glorysaber - I was able to resolve this by this method - https://stackoverflow.com/questions/63452257/xcode-12-beta-4-lexical-or-preprocessor-issue-header-file-not-found-simulato/63639145#63639145

**Comment by glorysaber** [comment] 2020-09-09 00:37
@shikhil-sevenlakes thanks for the link, but in this case it was not enough. Lumber Jack seems to be the only framework I am still having an issue with.

**Comment by glorysaber** [comment] 2020-09-10 21:46
@shikhil-sevenlakes Thanks! It actually solved my issue, turns out I had missed on of my dependent targets.

**Comment by ffried** [comment] 2020-10-01 13:50
I'm closing this since as far as I've seen the issues collected here have either been resolved, or aren't on our side.
If anyone still has issues, please open a new issue.

**Closed by ffried** 2020-10-01 13:50 UTC
