### ISSUE TITLE
Can't LOG_ASYNC_ENABLED NO - Ambiguous expansion of macro 'LOG_ASYNC_ENABLED'

### ISSUE THREAD

**Issue by Shasoosh** [CocoaLumberjack/CocoaLumberjack#833] opened 2017-02-12 15:27 UTC
Platform Name          osx
 Platform Version        10.12
 CocoaLumberjack Version . 3.0.0
 Integration Method    manually
 Xcode Version           Xcode 8.2.1
 Repro rate              all the time (100%)

I'm trying to cancel the async logs for debugging

This is the only place I import CocoaLumberjack:

#define LOG_ASYNC_ENABLED NO
#define LOG_LEVEL_DEF ddLogLevel
#import <CocoaLumberjack/CocoaLumberjack.h>

static const DDLogLevel ddLogLevel = DDLogLevelError;

I'm getting tons of Ambiguous expansion of macro 'LOG_ASYNC_ENABLED'

On previous versions I'd just edited that macro out in the library but now I'm using the framework. From what I've read the "Ambiguous expansion" is a bug in Xcode. 

Is there an easier way for me to disable Async instead of rebuilding the framework with custom settings?

**Comment by sryze** [comment] 2017-09-19 05:50
Same here. I use an older version of CocoaLumberjack (3.0) as a workaround.

**Comment by sryze** [comment] 2017-09-20 07:55
Commenting our relevant lines in `DDLogMacros.h` helped in my case:

```diff
diff --git a/Pods/CocoaLumberjack/Classes/DDLogMacros.h b/Pods/CocoaLumberjack/Classes/DDLogMacros.h
index 79ec421..05cbdef 100644
--- a/Pods/CocoaLumberjack/Classes/DDLogMacros.h
+++ b/Pods/CocoaLumberjack/Classes/DDLogMacros.h
@@ -23,16 +23,16 @@
 /**
  * The constant/variable/method responsible for controlling the current log level.
  **/
-#ifndef LOG_LEVEL_DEF
-    #define LOG_LEVEL_DEF ddLogLevel
-#endif
+// #ifndef LOG_LEVEL_DEF
+//     #define LOG_LEVEL_DEF ddLogLevel
+// #endif
 
 /**
  * Whether async should be used by log messages, excluding error messages that are always sent sync.
  **/
-#ifndef LOG_ASYNC_ENABLED
-    #define LOG_ASYNC_ENABLED YES
-#endif
+// #ifndef LOG_ASYNC_ENABLED
+//     #define LOG_ASYNC_ENABLED YES
+// #endif
 
 /**
  * These are the two macros that all other macros below compile into.

```

**Comment by sushichop** [comment] 2018-08-19 10:30
@Shasoosh @sryze 
Thanks for reporting.

This issue should be fixed by #784 . 
Could you try the latest CocoaLumberjack(3.4.2) and Swift 4.0?
At least, I confirmed `CocoaLumberjack(3.4.2)` and `Swift 4.0` worked fine with my project.
If you still encounter this problem let me know.

Thanks.

**Comment by sushichop** [comment] 2018-08-19 10:34
This issue may be related to #900 .

**Comment by bpoplauschi** [comment] 2018-08-20 13:55
Closing, based on the last comments. Feel free to reopen if the issue is not fixed with version 3.4.2 and Swift 4

**Closed by bpoplauschi** 2018-08-20 13:55 UTC

**Comment by ripperhe** [comment] 2019-06-19 03:09
@bpoplauschi 

| Info | Value |
| :-- | :-- |
| Platform Name | iOS |
| Platform Version | 12.3.1 |
| CocoaLumberjack Version | 3.5.2 |
| Integration Method | CocoaPods |
| Xcode Version | 10.2.1 |
| Repro rate | all the time (100%) |

`CocoaLumberjack(3.5.2)` still have this problem.A warning was also reported.

![Jietu20190619-102042](https://user-images.githubusercontent.com/13943595/59733785-a6e56a00-9281-11e9-9f06-89bea304f9b2.png)

My podfile is written like this.

![Jietu20190619-102138](https://user-images.githubusercontent.com/13943595/59734034-7d790e00-9282-11e9-9c9c-a19910524e5c.png)

**Comment by ripperhe** [comment] 2019-06-19 03:20
@bpoplauschi 
If I don't use `use_frameworks!`, `DDLog` work fine with my project. But I really need to use it.

**Comment by bpoplauschi** [comment] 2019-06-20 10:41
@ripperhe can you open a new issue? this one is pretty old. let's start fresh and make sure you provide all the info (required by the issue template)

**Comment by lutc** [comment] 2022-02-16 09:27
Also this warning can be fixed by undeffing:
`#import <CocoaLumberjack/CocoaLumberjack.h>

#undef LOG_ASYNC_ENABLED
#define LOG_ASYNC_ENABLED NO`
